name: Manual Workflow
on:
  workflow_dispatch:
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Rust Action
      id: rust_action
      uses: IlyaSelivanov/github-workflow@v1.0.3
    - name: Print out results
      run: echo ${{ steps.rust_action.output.results }}
